### ISSUE TITLE
[Gatsby] Going from article to article causes Giscus data to not load.

### ISSUE THREAD

**Issue by ceiphr** [giscus/react-giscus#2]
I don't know how to accurately describe this issue.

I went from one article to another, and comment data was missing for one of the posts. Each time I reacted to the post that was missing comment data, it created a new discussion with the title of the index of my site instead of using the post title.

For context:
- Discussions: https://github.com/ceiphr/ceiphr.com-comments/discussions
- Site: https://ceiphr.com/

I am more than happy to answer any questions, as I know this description isn't the most helpful.

**Comment by laymonage** [comment]
Hey, I'm guessing it's because react-giscus has already loaded before react-helmet has finished changing the page's title. Maybe you can try adding `console.log(document.title)` and see if that's the case?

Also, does Helmet have a way to notify you when it finishes loading? If not, I'm not sure if this would work, but maybe you can try something like:

```jsx
const [, rerender] = useState({});

useEffect(() => {
  rerender({});
}, [document.title]);
```

**Comment by ceiphr** [comment]
In Gatsby to build when `document` is called, I need to wrap the `useEffect` like this:

```tsx
if (typeof window !== "undefined") {
  const [title, setTitle] = React.useState("")

  React.useEffect(() => {
    if (document.title !== title) setTitle(document.title)
  }, [title, document.title])
}
```

From what I can tell, it is working, but I will do some more testing in the morning to confirm. Thank you!

**Comment by laymonage** [comment]
FYI [you shouldn't use hooks inside a conditional](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level).
It's better to do something like:

```jsx
const documentTitle = typeof window !== 'undefined' ? document.title : '';
const [title, setTitle] = React.useState(documentTitle);

React.useEffect(() => {
  if (documentTitle !== title) setTitle(document.title);
}, [documentTitle, title]
```

On second thought, does this work?

```jsx
const documentTitle = typeof window !== 'undefined' ? document.title : '';

return (
  <Giscus
    ...
    repo="..."
    mapping="specific"
    term={documentTitle}
    />
);
```

**Comment by ceiphr** [comment]
> FYI you shouldn't use hooks inside a conditional.

Noted, thank you!

> On second thought, does this work?

That approach gave me a great idea. I'm now mimicking my page title with data pulled from GraphQL, like this:

```tsx
return (
  <Giscus
    ...
    repo="..."
    mapping="specific"
    term={`${post.frontmatter.title} | ${data.site.siteMetadata.title}`}
  />
);
```

This way, no matter what the `document.title` is, Giscus will know what post it's on according to the parent component's contents. Thank you for the help!
